# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: default-reader-role-binding
subjects:
  - kind: User
    name: "*"
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: default-reader
  apiGroup: ""
