# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: descheduler-role-binding
subjects:
  - kind: Group
    name: kube-system:descheduler-sa
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: descheduler-cluster-role
  apiGroup: ""
