# basic readonly
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: dev-manager-role-binding
subjects:
  - kind: Group
    name: oidc:dev-manager
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cluster-dev-manager
  apiGroup: ""
