apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
apiGroup: rbac.authorization.k8s.io
metadata:
  name: kube-system-readall-role-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kube-system
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cluster-read-all
  apiGroup: ""
