apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: scheduler-role-binding
subjects:
  - kind: User
    name: system:scheduler
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: scheduler
  apiGroup: ""
