apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
apiGroup: rbac.authorization.k8s.io
metadata:
  name: scheduler-role-binding
subjects:
  - kind: User
    name: system:scheduler
roleRef:
  kind: ClusterRole
  name: scheduler
  apiVersion: rbac.authorization.k8s.io/v1
