# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
apiGroup: rbac.authorization.k8s.io
metadata:
  name: wildcard-services-role-binding
subjects:
  - kind: User
    name: "*"
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: services-reader
  apiGroup: ""
