---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-controller-manager
rules:
  -
    apiGroups:
      - "*"
    resources: ["*"]
    verbs: ["*"]
  - nonResourceURLs: [""]
    verbs: ["*"]
